spring.mail.host=smtp.naver.com
spring.mail.port=587

# \uc774\uba54\uc77c Id/Pw \uc785\ub825
spring.mail.username=\uc774\uba54\uc77c \uc544\uc774\ub514
spring.mail.password=\uc774\uba54\uc77c \ube44\ubc00\ubc88\ud638

spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.transport.protocol=smtp

spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
