spring.application.name=campProject


# springdoc(swagger) cofig error patch
# Swagger API \ubb38\uc11c\ub97c \ud504\ub808\uc784\uc6cc\ud06c \ubc29\uc2dd\uc73c\ub85c \uc804\ub2ec
server.forward-headers-strategy=FRAMEWORK
# URL \ub9e4\uce6d \ubc29\uc2dd \uc124\uc815 (ANT_PATH_MATCHER)
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

#port
server.port=8181

# context path
server.servlet.context-path=/campProject

# devtools
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# logging
logging.config=classpath:log4j2.properties

# log4jdbc
# Oracle DataSource \uc5f0\uacb0 \uc124\uc815
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=camp
spring.datasource.password=camp

# Hikari dataSource
spring.datasource.hikari.pool-name=hikariCP
spring.datasource.hikari.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.hikari.jdbc-url=jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.hikari.username=camp
spring.datasource.hikari.password=camp

spring.session.store-type=jdbc

# myBatis
mybatis.mapper-locations=classpath:/mapper/*.xml

# snake case <=> camel case
mybatis.configuration.map-underscore-to-camel-case=true

mybatis.type-aliases-package=com.javateam.campProject.domain

# thymeleaf
spring.thymeleaf.cache=false

# static resources path
# webjars & spring boot
# : https://www.webjars.org/documentation#springboot
spring.mvc.static-path-pattern=/**

spring.web.resources.static-locations[0]=classpath:/static/
spring.web.resources.static-locations[1]=classpath:/META-INF/resources/webjars/

spring.web.resources.add-mappings=true

# jpa
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# FileUpload Path
# Summernote Content Image Updload Path
# fileUpload.path=/static/board_upFile/file/
# imageUpload.path=/static/board_upFile/image/
# 상대경로 사용 시 에러 발생하여 PC에 맞는 주소로 변경하여 사용
fileUpload.path=D:/coding/work/project2/camp_project/campProject/src/main/resources/static/board_upFile/file/
imageUpload.path=D:/coding/work/project2/camp_project/campProject/src/main/resources/static/board_upFile/image/

# FileUpload Max size(\ucd5c\ub300 \ud06c\uae30:\uc5c5\ub85c\ub4dc \ud55c\uacc4\ub7c9)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# session timeout(\uc81c\ud55c\uc2dc\uac04) : 1\uc2dc\uac04(3600\ucd08)
server.servlet.session.timeout=3600

# \uba54\ud0c0 \ud30c\uc77c \ubaa8\ub4c8\ud654
# application-<Profile name>.properties
spring.profiles.include=oauth-naver,oauth-google,email

# 캠핑 이미지 저장소
campImg.storePath=D:/coding/work/crawl/campImage/