spring.application.name=campProject

# Oracle DataSource \uc5f0\uacb0 \uc124\uc815
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=camp
spring.datasource.password=camp

# Hikari dataSource
spring.datasource.hikari.pool-name=hikariCP
spring.datasource.hikari.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.hikari.jdbc-url=jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.hikari.username=camp
spring.datasource.hikari.password=camp

# springdoc(swagger) cofig error patch
# Swagger API \ubb38\uc11c\ub97c \ud504\ub808\uc784\uc6cc\ud06c \ubc29\uc2dd\uc73c\ub85c \uc804\ub2ec
server.forward-headers-strategy=FRAMEWORK
# URL \ub9e4\uce6d \ubc29\uc2dd \uc124\uc815 (ANT_PATH_MATCHER)
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

#port
server.port=8181

# context path
server.servlet.context-path=/campProject

# devtools
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# logging
logging.config=classpath:log4j2.properties

spring.session.store-type=jdbc

# myBatis
mybatis.mapper-locations=classpath:/mapper/*.xml

# snake case <=> camel case
mybatis.configuration.map-underscore-to-camel-case=true

mybatis.type-aliases-package=com.javateam.campProject.domain

# thymeleaf
spring.thymeleaf.cache=false

# static resources path
# webjars & spring boot
# : https://www.webjars.org/documentation#springboot
spring.mvc.static-path-pattern=/**

spring.web.resources.static-locations[0]=classpath:/static/
spring.web.resources.static-locations[1]=classpath:/META-INF/resources/webjars/

spring.web.resources.add-mappings=true

# jpa
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# FileUpload Path
# Summernote Content Image Updload Path
# fileUpload.path=/static/board_upFile/file/
# imageUpload.path=/static/board_upFile/image/
# \u00ec\u0083\u0081\u00eb\u008c\u0080\u00ea\u00b2\u00bd\u00eb\u00a1\u009c \u00ec\u0082\u00ac\u00ec\u009a\u00a9 \u00ec\u008b\u009c \u00ec\u0097\u0090\u00eb\u009f\u00ac \u00eb\u00b0\u009c\u00ec\u0083\u009d\u00ed\u0095\u0098\u00ec\u0097\u00ac PC\u00ec\u0097\u0090 \u00eb\u00a7\u009e\u00eb\u008a\u0094 \u00ec\u00a3\u00bc\u00ec\u0086\u008c\u00eb\u00a1\u009c \u00eb\u00b3\u0080\u00ea\u00b2\u00bd\u00ed\u0095\u0098\u00ec\u0097\u00ac \u00ec\u0082\u00ac\u00ec\u009a\u00a9
fileUpload.path=D:/coding/work/project2/camp_project/campProject/src/main/resources/static/board_upFile/file/
imageUpload.path=D:/coding/work/project2/camp_project/campProject/src/main/resources/static/board_upFile/image/

# FileUpload Max size(\ucd5c\ub300 \ud06c\uae30:\uc5c5\ub85c\ub4dc \ud55c\uacc4\ub7c9)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# session timeout(\uc81c\ud55c\uc2dc\uac04) : 1\uc2dc\uac04(3600\ucd08)
server.servlet.session.timeout=3600

# \uba54\ud0c0 \ud30c\uc77c \ubaa8\ub4c8\ud654
# application-<Profile name>.properties
spring.profiles.include=oauth-naver,oauth-google,email

## camp Image store repo
## \uc0c1\ub300\uacbd\ub85c \uc0ac\uc6a9 \uc2dc \uc5d0\ub7ec \ubc1c\uc0dd\ud558\uc5ec PC\uc5d0 \ub9de\ub294 \uc8fc\uc18c\ub85c \ubcc0\uacbd\ud558\uc5ec \uc0ac\uc6a9
#campImg.storePath=C:/Users/USER/Desktop/programming/works/crawling/
campImg.storePath=D:/coding/work/crawl/campImage/
