-- 캠핑장 이미지 정보 테이블
CREATE TABLE CAMP_IMG_TBL (
    ID   NUMBER(10) PRIMARY KEY,
	C_NO NUMBER NOT NULL,
	IMG_KIND CHAR(1), -- mainImage : M, -- subImage : S
	IMG_NAME VARCHAR2(200)
);

COMMENT ON COLUMN CAMP_IMG_TBL.ID IS 'PK(기본키)';
COMMENT ON COLUMN CAMP_IMG_TBL.C_NO IS '고캠핑 CONTENT_ID (C_NO)';
COMMENT ON COLUMN CAMP_IMG_TBL.IMG_KIND IS '메인 이미지/서브 이미지 여부';
COMMENT ON COLUMN CAMP_IMG_TBL.IMG_NAME IS '이미지 파일명(확장자 포함)';

CREATE SEQUENCE CAMP_IMG_TBL_SEQ
MINVALUE 1
MAXVALUE 9999999999
INCREMENT BY 1
START WITH 1
NOCYCLE
NOCACHE;