CREATE TABLE CAMP_SITE_TBL (
	C_NO NUMBER PRIMARY KEY,
	SITE_CONTENT VARCHAR2(1000),
	SITE NUMBER DEFAULT 0,
	PET_YN CHAR DEFAULT 'N'
);

-- 개별 예약 테이블
CREATE TABLE CAMP_RESEVATION_TBL (
	ID NUMBER PRIMARY KEY,
	CUSTOMER VARCHAR2(20),
	RESERVED_C_NO NUMBER,
	RESERVED_SITE NUMBER,
	REVERSED_BEGIN_DATE DATE,
	REVERSED_END_DATE DATE
);

