CREATE TABLE CAMP_RESERVATION_TBL (
	CAMP_C_NO NUMBER,
	CAMP_NAME VARCHAR2(100 CHAR),
	CHECK_IN DATE,
	CHECK_OUT DATE,
	USER_NAME VARCHAR2(100),
	USER_EMAIL VARCHAR2(50),
	USER_PHONE VARCHAR2(13));

COMMENT ON COLUMN CAMP_RESERVATION_TBL.CAMP_C_NO IS '캠핑장 C_NUMBER';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.CAMP_NAME IS '캠핑장명';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.CHECK_IN IS '체크인 날짜';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.CHECK_OUT IS '체크아웃 날짜';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.USER_NAME IS '회원명';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.USER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.USER_PHONE IS '회원 전화번호';
