CREATE TABLE CAMP_REVIEW_TBL (
	CAMP_NAME VARCHAR2(100 CHAR) PRIMARY KEY,
	AVG_RATING NUMBER(3,2) DEFAULT 0,
	REVIEWS CLOB
);

CREATE TABLE CAMP_REVIEW_TBL2 (
	ID NUMBER PRIMARY KEY,
	CAMP_NAME VARCHAR2(100 CHAR),
	AVG_RATING NUMBER(3,2) DEFAULT 0,
	REVIEWS VARCHAR2(4000),
	PREDICT NUMBER(1)
);

CREATE SEQUENCE CAMP_REVIEW_TBL_SEQ
MINVALUE 1
MAXVALUE 9999999999
INCREMENT BY 1
START WITH 1
NOCYCLE
NOCACHE;