-- 개인 캠핑장 예약현황 테이블
CREATE TABLE CAMP_RESERVATION_TBL (
	ID NUMBER PRIMARY KEY,
	CAMP_ID NUMBER(10,0),
	CAMP_C_NO NUMBER,
	CAMP_NAME VARCHAR2(100 CHAR),
	CHECK_IN DATE,
	CHECK_OUT DATE,
	USER_NAME VARCHAR2(100),
	USER_EMAIL VARCHAR2(50),
	USER_PHONE VARCHAR2(13));

COMMENT ON COLUMN CAMP_RESERVATION_TBL.ID IS '기본키';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.CAMP_ID IS '캠핑장 아이디';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.CAMP_C_NO IS '캠핑장 C_NUMBER';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.CAMP_NAME IS '캠핑장명';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.CHECK_IN IS '체크인 날짜';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.CHECK_OUT IS '체크아웃 날짜';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.USER_NAME IS '회원명';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.USER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN CAMP_RESERVATION_TBL.USER_PHONE IS '회원 전화번호';

CREATE SEQUENCE RESERVATION_SEQ
MINVALUE 1
MAXVALUE 9999999999
INCREMENT BY 1
START WITH 1
NOCYCLE
NOCACHE;

--------------------------------------------------------------------

-- 전체 캠핑장 예약현황 테이블(누적현황만 집계)
CREATE TABLE CAMP_TOT_RESERVATION_TBL (
	CAMP_ID NUMBER(10,0) PRIMARY KEY,
--	CAMP_C_NO NUMBER,
	SITE NUMBER DEFAULT 0,
	AVAIL_SITE NUMBER DEFAULT 0
);

COMMENT ON COLUMN CAMP_TOT_RESERVATION_TBL.CAMP_ID IS '캠핑장 아이디';
-- COMMENT ON COLUMN CAMP_TOT_RESERVATION_TBL.CAMP_C_NO IS '캠핑장 C_NUMBER';
COMMENT ON COLUMN CAMP_TOT_RESERVATION_TBL.SITE IS '캠핑장 사이트 갯수(전체 캠핑 공간 수)';
COMMENT ON COLUMN CAMP_TOT_RESERVATION_TBL.AVAIL_SITE IS '캠핑장 예약 가능 사이트 갯수';

-------------------------------------------------------------------------------

SELECT CHECK_IN, CHECK_OUT, USER_NAME, USER_EMAIL, USER_PHONE
  FROM CAMP_RESERVATION_TBL
 WHERE CHECK_IN =#{checkIn} AND CHECK_OUT=#{checkOut} AND USER_NAME=#{userName} AND USER_EMAIL=#{userEmail} AND USER_PHONE=#{userPhone}

UPDATE CAMP_TOT_RESERVATION_TBL
   SET SITE = 10
 WHERE SITE = 0;

UPDATE CAMP_TOT_RESERVATION_TBL
   SET AVAIL_SITE = 0
 WHERE CAMP_ID = 2445;

 SELECT c_no, site
   from CAMP_SITE_TBL site
  where c_no in (select c_no )

-- count가 0이면 예약 가능, 1이면 예약 불가능
-- SELECT CHECK_IN, CHECK_OUT, USER_NAME, USER_EMAIL, USER_PHONE
SELECT COUNT(*)
 	FROM CAMP_RESERVATION_TBL
  WHERE USER_NAME= '홍길동'
 	AND USER_EMAIL='tgdcom7@naver.com'
 	AND USER_PHONE='010-1111-1111'
 	AND CHECK_IN>='2024-12-02'
 	AND CHECK_OUT<='2024-12-05';