-- 테이블 PK 시퀀스
CREATE SEQUENCE inqulry_board_upFile_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE;

CREATE TABLE INQUIRY_BOARD_UPFILE (
	ID NUMBER(10,0) PRIMARY KEY,
	FILENAME NVARCHAR2(300) NOT NULL,
	SAVE_FILENAME NVARCHAR2(500) NOT NULL,
	FILE_PATH NVARCHAR2(500) NOT NULL,
	CONTENT_TYPE NVARCHAR2(10),
	FILE_SIZE NUMBER(20,0) DEFAULT 0,
	REGDATE DATE DEFAULT SYSDATE
);