CREATE TABLE USER_TBL (
ID VARCHAR2(20) PRIMARY KEY,
PW VARCHAR2(100) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
GENDER CHAR NOT NULL,
EMAIL VARCHAR2(50) NOT NULL UNIQUE,
PHONE VARCHAR2(13) NOT NULL,
ZIP CHAR(5),
ROAD_ADDRESS NVARCHAR2(100),
JIBUN_ADDRESS NVARCHAR2(100),
DETAIL_ADDRESS NVARCHAR2(50),
BIRTHDAY DATE,
JOINDATE DATE DEFAULT CURRENT_DATE,
MEMBERTYPE VARCHAR2(20),
BUSINESSNUM VARCHAR2(20)
);


COMMENT ON COLUMN USER_TBL.ID IS '아이디';
COMMENT ON COLUMN USER_TBL.PW IS '비밀번호';
COMMENT ON COLUMN USER_TBL.NAME IS '이름';
COMMENT ON COLUMN USER_TBL.GENDER IS '성별';
COMMENT ON COLUMN USER_TBL.EMAIL IS '이메일';
COMMENT ON COLUMN USER_TBL.PHONE IS '휴대폰';
COMMENT ON COLUMN USER_TBL.ZIP IS '우편번호';
COMMENT ON COLUMN USER_TBL.ROAD_ADDRESS IS '도로명 주소';
COMMENT ON COLUMN USER_TBL.JIBUN_ADDRESS IS '지번 주소';
COMMENT ON COLUMN USER_TBL.DETAIL_ADDRESS IS '상세 주소';
COMMENT ON COLUMN USER_TBL.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN USER_TBL.JOINDATE IS '가입일';
COMMENT ON COLUMN USER_TBL.MEMBERTYPE IS '회원종류';
COMMENT ON COLUMN USER_TBL.BUSINESSNUM IS '사업자 번호';
COMMENT ON COLUMN USER_TBL.STATUS IS '활동 정지 여부'

/* 참고) 성별 제약조건은 아래와 같이 작성할 수도 있습니다. */
ALTER TABLE USER_TBL ADD CONSTRAINT USER_TBL_GENDER_CK CHECK ( gender IN ( 'm', 'f' ) );