/* 테이블 조인 */
SELECT U.ID, U.NAME, U.EMAIL, R.ROLE
  FROM USER_TBL U, USER_ROLES R
 WHERE U.ID = R.USERID;

/* 회원 role별 조회 */
SELECT U.ID id, U.NAME name, U.EMAIL email, R.ROLE role
  FROM USER_TBL U, USER_ROLES R
 WHERE U.ID = R.USERID
   AND R.ROLE='ROLE_USER';