CREATE TABLE USER_ROLES (
    USER_ROLE_NUM NUMBER(20)   NOT NULL,
    USERID        VARCHAR2(20) NOT NULL,
    ROLE          VARCHAR2(45) NOT NULL,
    PRIMARY KEY (USER_ROLE_NUM),
    CONSTRAINT  FK_USERID FOREIGN KEY (USERID)
    REFERENCES  USER_TBL (ID)
);

CREATE SEQUENCE USER_ROLES_SEQ
    START     WITH 1
    INCREMENT BY 1
    MAXVALUE  99999999
    NOCYCLE;